### PR TITLE
Fixed 2 bugs

### PR DESCRIPTION
**Pull request by ASPJulien**
- Fixe crash with "watch" button
- Lock resize-window on every window

### CODE REVIEW

**Comment by zbroderson** [comment]
Great!  Can’t believe I missed the issue with the watch button.  Will merge in a few days once I get back to my computer.

**Comment by zbroderson** [comment]
@ASPJulien Do you think you could change the `try/catch` to a null check?  I cast the `SelectedValue` to an `AnimeInfo` in a safe manner, so a quick null-check should work and should keep the program from throwing an exception.

**Comment by ASPJulien** [comment]
yup I will check that

**Comment by ASPJulien** [comment]
Should be good now

**Comment by ASPJulien** [comment]
I wasn't able to check if URL != null, so I check if a anime was selected

**Comment by zbroderson** [comment]
Great! Exactly what I wanted.  Will be merging shortly.

**Comment by ASPJulien** [comment]
I think you forgot this pull 😓

**Comment by zbroderson** [comment]
It appears I did.  Sorry!  I have moved to linux after the creation of this app, so it a bit of hassle to setup a windows boot.  I should have time this weekend.

**Comment by ASPJulien** [comment]
np 👍

**Pull request merged**
